// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: proto/donuts.proto

package donut_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Donut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Id    string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Donut) Reset() {
	*x = Donut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_donuts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Donut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Donut) ProtoMessage() {}

func (x *Donut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donuts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Donut.ProtoReflect.Descriptor instead.
func (*Donut) Descriptor() ([]byte, []int) {
	return file_proto_donuts_proto_rawDescGZIP(), []int{0}
}

func (x *Donut) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Donut) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Donut) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Donut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DonutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DonutRequest) Reset() {
	*x = DonutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_donuts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DonutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DonutRequest) ProtoMessage() {}

func (x *DonutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donuts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DonutRequest.ProtoReflect.Descriptor instead.
func (*DonutRequest) Descriptor() ([]byte, []int) {
	return file_proto_donuts_proto_rawDescGZIP(), []int{1}
}

func (x *DonutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Donuts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donuts []*Donut `protobuf:"bytes,1,rep,name=donuts,proto3" json:"donuts,omitempty"`
}

func (x *Donuts) Reset() {
	*x = Donuts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_donuts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Donuts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Donuts) ProtoMessage() {}

func (x *Donuts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donuts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Donuts.ProtoReflect.Descriptor instead.
func (*Donuts) Descriptor() ([]byte, []int) {
	return file_proto_donuts_proto_rawDescGZIP(), []int{2}
}

func (x *Donuts) GetDonuts() []*Donut {
	if x != nil {
		return x.Donuts
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_donuts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_proto_donuts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_proto_donuts_proto_rawDescGZIP(), []int{3}
}

func (x *Version) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

var File_proto_donuts_proto protoreflect.FileDescriptor

var file_proto_donuts_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x57, 0x0a, 0x05, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x0c, 0x44, 0x6f,
	0x6e, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x28,
	0x0a, 0x06, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x06, 0x64, 0x6f, 0x6e, 0x75,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74,
	0x52, 0x06, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x22, 0x21, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xaf, 0x01, 0x0a, 0x09,
	0x44, 0x6f, 0x6e, 0x75, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x23, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x44, 0x6f, 0x6e, 0x75, 0x74, 0x12, 0x0d, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x22, 0x00, 0x12, 0x25,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x12, 0x0d, 0x2e, 0x44, 0x6f,
	0x6e, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x44, 0x6f, 0x6e,
	0x75, 0x74, 0x73, 0x22, 0x00, 0x12, 0x24, 0x0a, 0x09, 0x4d, 0x61, 0x6b, 0x65, 0x44, 0x6f, 0x6e,
	0x75, 0x74, 0x12, 0x06, 0x2e, 0x44, 0x6f, 0x6e, 0x75, 0x74, 0x1a, 0x0d, 0x2e, 0x44, 0x6f, 0x6e,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x08, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x22, 0x5a,
	0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x31, 0x6e, 0x74,
	0x61, 0x78, 0x65, 0x37, 0x37, 0x30, 0x72, 0x2f, 0x64, 0x6f, 0x6e, 0x75, 0x74, 0x2d, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_donuts_proto_rawDescOnce sync.Once
	file_proto_donuts_proto_rawDescData = file_proto_donuts_proto_rawDesc
)

func file_proto_donuts_proto_rawDescGZIP() []byte {
	file_proto_donuts_proto_rawDescOnce.Do(func() {
		file_proto_donuts_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_donuts_proto_rawDescData)
	})
	return file_proto_donuts_proto_rawDescData
}

var file_proto_donuts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_donuts_proto_goTypes = []interface{}{
	(*Donut)(nil),         // 0: Donut
	(*DonutRequest)(nil),  // 1: DonutRequest
	(*Donuts)(nil),        // 2: Donuts
	(*Version)(nil),       // 3: Version
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_proto_donuts_proto_depIdxs = []int32{
	0, // 0: Donuts.donuts:type_name -> Donut
	1, // 1: DonutShop.GetDonut:input_type -> DonutRequest
	1, // 2: DonutShop.GetDonuts:input_type -> DonutRequest
	0, // 3: DonutShop.MakeDonut:input_type -> Donut
	4, // 4: DonutShop.GetVersion:input_type -> google.protobuf.Empty
	0, // 5: DonutShop.GetDonut:output_type -> Donut
	2, // 6: DonutShop.GetDonuts:output_type -> Donuts
	1, // 7: DonutShop.MakeDonut:output_type -> DonutRequest
	3, // 8: DonutShop.GetVersion:output_type -> Version
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_donuts_proto_init() }
func file_proto_donuts_proto_init() {
	if File_proto_donuts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_donuts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Donut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_donuts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DonutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_donuts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Donuts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_donuts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_donuts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_donuts_proto_goTypes,
		DependencyIndexes: file_proto_donuts_proto_depIdxs,
		MessageInfos:      file_proto_donuts_proto_msgTypes,
	}.Build()
	File_proto_donuts_proto = out.File
	file_proto_donuts_proto_rawDesc = nil
	file_proto_donuts_proto_goTypes = nil
	file_proto_donuts_proto_depIdxs = nil
}
